/**
 * TypeScript type definitions for the Enterprise Hybrid Data Agent.
 *
 * These interfaces mirror the Pydantic models defined in backend/models/schemas.py.
 * Any changes to the backend API contract must be reflected here.
 *
 * Naming convention:
 *   - Backend snake_case field names are preserved (not converted to camelCase)
 *     because the FastAPI backend returns JSON with snake_case keys and we
 *     consume them directly without a transformation layer.
 */

// ---------------------------------------------------------------------------
// Pipeline types
// ---------------------------------------------------------------------------

/**
 * Which retrieval pipeline was used to answer the query.
 * Mirrors backend PipelineType enum (str).
 *
 * Using a string union type rather than a TypeScript enum to:
 *   1. Avoid TypeScript enum pitfalls (reverse mapping, const enum issues)
 *   2. Serialize cleanly to/from JSON without mapping
 *   3. Allow direct comparison with backend response strings
 */
export type PipelineType = "SQL" | "VECTOR" | "HYBRID";

// ---------------------------------------------------------------------------
// API request/response shapes
// ---------------------------------------------------------------------------

/**
 * Request payload for POST /api/query.
 * Mirrors backend QueryRequest Pydantic model.
 */
export interface QueryRequest {
  /** Natural language question (3–2000 characters, non-blank). */
  question: string;
}

/**
 * Intermediate pipeline artifacts returned alongside the answer.
 * Mirrors backend Artifacts Pydantic model.
 *
 * All fields are optional (null in JSON) — the frontend must check
 * for null/undefined before rendering each artifact section:
 *   - SQL fields populated for SQL and HYBRID pipelines
 *   - Vector fields populated for VECTOR and HYBRID pipelines
 */
export interface Artifacts {
  // SQL pipeline artifacts
  /** The SQL SELECT statement generated by the LLM and executed against SQLite. */
  sql_query: string | null;

  /**
   * Raw rows returned by the SQL query, as a list of objects.
   * Keys are the (cryptic) SQLite column names; values are the cell values.
   * Column names may be computed aliases (e.g., "total_revenue_m").
   */
  sql_results: Record<string, unknown>[] | null;

  /** Number of rows returned by the SQL query. */
  sql_row_count: number | null;

  // Vector pipeline artifacts
  /**
   * Text content of the top-k document chunks retrieved from ChromaDB,
   * ordered by relevance (most relevant first / lowest cosine distance first).
   */
  retrieved_chunks: string[] | null;

  /**
   * Cosine distance scores for each retrieved chunk.
   * Lower values indicate higher semantic similarity.
   * Parallel array to retrieved_chunks and chunk_metadata.
   */
  chunk_scores: number[] | null;

  /**
   * Metadata objects for each retrieved chunk.
   * Typical keys: source, chunk_id, section, date, author, departments_referenced.
   * Parallel array to retrieved_chunks and chunk_scores.
   */
  chunk_metadata: Record<string, string>[] | null;
}

/**
 * Full response returned by POST /api/query.
 * Mirrors backend QueryResponse Pydantic model.
 */
export interface QueryResponse {
  /** Natural language answer synthesized by the LLM. */
  answer: string;

  /** Which pipeline was used to generate this answer. */
  pipeline: PipelineType;

  /**
   * Intermediate pipeline artifacts for transparency and debugging.
   * Fields are null when not applicable to the pipeline used.
   */
  artifacts: Artifacts;

  /**
   * Total server-side processing time in milliseconds.
   * Null if not measured (should always be present in practice).
   */
  processing_time_ms: number | null;

  /**
   * Error message if the pipeline encountered a recoverable error
   * but still returned a partial answer. Null on full success.
   */
  error: string | null;
}

/**
 * Response returned by GET /api/health.
 * Mirrors backend HealthResponse Pydantic model.
 */
export interface HealthResponse {
  /** Overall service status: "ok" when all components are healthy. */
  status: "ok" | "degraded" | string;

  /**
   * Per-component status map.
   * Keys: "sqlite", "chromadb", "openai"
   * Values: "ok (...)" or "degraded: ..." or "unavailable: ..."
   */
  components: Record<string, string>;

  /** API version string (e.g., "1.0.0"). */
  version: string;
}

// ---------------------------------------------------------------------------
// Frontend-only types (not present in backend schemas)
// ---------------------------------------------------------------------------

/**
 * Role of a message in the chat conversation.
 *   "user"  — message sent by the human user
 *   "agent" — response generated by the AI agent
 */
export type MessageRole = "user" | "agent";

/**
 * A single message in the chat conversation.
 *
 * This is a frontend-only type — it combines the user's question,
 * the agent's response, and UI state (loading, timestamps) into a
 * single object for easy rendering in the chat window.
 */
export interface ChatMessage {
  /**
   * Unique identifier for this message.
   * Generated client-side using crypto.randomUUID() or Date.now().
   * Used as the React key prop for stable list rendering.
   */
  id: string;

  /** Whether this is a user message or an agent response. */
  role: MessageRole;

  /**
   * The text content of the message.
   *   - For user messages: the question text as typed.
   *   - For agent messages: the synthesized answer from QueryResponse.answer.
   */
  content: string;

  /**
   * ISO 8601 timestamp when this message was created (client-side).
   * Used for display and for ordering messages in the chat window.
   */
  timestamp: string;

  /**
   * Whether this agent message is currently being generated.
   * True while the API request is in-flight; false once the response arrives.
   * Only relevant for agent messages (always false for user messages).
   */
  isLoading?: boolean;

  /**
   * The full QueryResponse from the backend, stored on agent messages.
   * Used by the ArtifactsPanel and PipelineBadge components to render
   * pipeline type, generated SQL, retrieved chunks, scores, etc.
   * Null for user messages and while isLoading is true.
   */
  queryResponse?: QueryResponse | null;

  /**
   * Error message to display if the API call failed entirely
   * (network error, server error, etc.).
   * Distinct from QueryResponse.error which is a partial pipeline error.
   * Null when no error occurred.
   */
  errorMessage?: string | null;
}

// ---------------------------------------------------------------------------
// API client types
// ---------------------------------------------------------------------------

/**
 * Options for the API client's fetch wrapper.
 */
export interface FetchOptions {
  /** AbortController signal for request cancellation. */
  signal?: AbortSignal;
  /** Additional headers to merge with the defaults. */
  headers?: Record<string, string>;
}

/**
 * Structured error thrown by the API client.
 * Carries the HTTP status code and parsed response body for
 * proper error display in the UI.
 */
export interface ApiErrorDetails {
  /** HTTP status code (e.g., 422, 500). 0 for network errors. */
  status: number;
  /** Human-readable error message. */
  message: string;
  /** Raw response body (if parseable as JSON). */
  body?: unknown;
}
