"""
Pydantic request/response models for the Enterprise Hybrid Agent API.

These models define the contract between the FastAPI backend and the
React frontend.  Every field is explicitly typed and documented so that
FastAPI's auto-generated OpenAPI schema is self-explanatory.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class PipelineType(str, Enum):
    """
    Which retrieval pipeline was used to answer the query.

    Inheriting from `str` ensures the value serialises as a plain JSON string
    ("SQL", "VECTOR", "HYBRID") rather than an integer ordinal, so the
    frontend can consume it directly without any mapping layer.
    """

    SQL = "SQL"
    VECTOR = "VECTOR"
    HYBRID = "HYBRID"


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------


class QueryRequest(BaseModel):
    """
    Payload sent by the frontend when the user submits a question.
    """

    question: str = Field(
        ...,
        min_length=3,
        max_length=2000,
        description=(
            "Natural language question to be answered by the agent. "
            "Must be between 3 and 2000 characters."
        ),
        examples=["What was the total revenue for department D_402 in fiscal year 2025?"],
    )

    @field_validator("question", mode="before")
    @classmethod
    def strip_and_validate_question(cls, v: Any) -> str:
        """Strip surrounding whitespace and reject blank strings."""
        if not isinstance(v, str):
            raise ValueError("question must be a string")
        stripped = v.strip()
        if not stripped:
            raise ValueError("question must not be blank or whitespace-only")
        return stripped

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "question": (
                        "What was the total revenue for department D_402 "
                        "in fiscal year 2025?"
                    )
                },
                {"question": "What is Project Phoenix and what are its expected outcomes?"},
                {
                    "question": (
                        "Why did department D_402's EBITDA margin improve "
                        "from Q3 to Q4 2025, and what strategic initiative drove it?"
                    )
                },
            ]
        }
    }


# ---------------------------------------------------------------------------
# Artifact models — intermediate pipeline outputs
# ---------------------------------------------------------------------------


class SQLArtifacts(BaseModel):
    """
    Artifacts produced by the Text-to-SQL pipeline.
    All fields are optional because this model is reused inside the combined
    Artifacts wrapper where SQL fields may be absent (e.g. pure Vector query).
    """

    sql_query: Optional[str] = Field(
        default=None,
        description="The SQL SELECT statement generated by the LLM and executed against SQLite.",
        examples=["SELECT SUM(rev_raw_m) FROM erp_fin_qtr_export WHERE dept_id_ref = 'D_402' AND fy_yr = 2025"],
    )
    sql_results: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description=(
            "Raw rows returned by the SQL query, serialised as a list of dicts "
            "(column name → value). Empty list if the query returned no rows."
        ),
        examples=[[{"SUM(rev_raw_m)": 98.5}]],
    )
    sql_row_count: Optional[int] = Field(
        default=None,
        description="Number of rows returned by the SQL query.",
        examples=[1],
    )


class VectorArtifacts(BaseModel):
    """
    Artifacts produced by the Vector Search pipeline.
    """

    retrieved_chunks: Optional[list[str]] = Field(
        default=None,
        description=(
            "Text content of the top-k document chunks retrieved from ChromaDB, "
            "ordered by relevance (most relevant first)."
        ),
    )
    chunk_scores: Optional[list[float]] = Field(
        default=None,
        description=(
            "Cosine distance scores for each retrieved chunk (lower = more similar). "
            "Parallel array to retrieved_chunks."
        ),
        examples=[[0.1823, 0.2541, 0.3102]],
    )
    chunk_metadata: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description=(
            "Metadata dicts for each retrieved chunk (source document, section, date, etc.). "
            "Parallel array to retrieved_chunks."
        ),
    )

    @model_validator(mode="after")
    def validate_parallel_arrays(self) -> "VectorArtifacts":
        """
        Ensure retrieved_chunks, chunk_scores, and chunk_metadata have the
        same length when all three are provided.
        """
        arrays = {
            "retrieved_chunks": self.retrieved_chunks,
            "chunk_scores": self.chunk_scores,
            "chunk_metadata": self.chunk_metadata,
        }
        populated = {k: v for k, v in arrays.items() if v is not None}
        if len(populated) > 1:
            lengths = {k: len(v) for k, v in populated.items()}
            if len(set(lengths.values())) > 1:
                raise ValueError(
                    f"retrieved_chunks, chunk_scores, and chunk_metadata must have "
                    f"the same length. Got: {lengths}"
                )
        return self


class Artifacts(BaseModel):
    """
    Combined artifacts container returned in every QueryResponse.

    SQL fields are populated for SQL and HYBRID pipelines.
    Vector fields are populated for VECTOR and HYBRID pipelines.
    All fields are optional — the frontend checks for None before rendering.
    """

    # SQL pipeline artifacts
    sql_query: Optional[str] = Field(
        default=None,
        description="The SQL SELECT statement generated by the LLM.",
    )
    sql_results: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Raw rows returned by the SQL query as a list of dicts.",
    )
    sql_row_count: Optional[int] = Field(
        default=None,
        description="Number of rows returned by the SQL query.",
    )

    # Vector pipeline artifacts
    retrieved_chunks: Optional[list[str]] = Field(
        default=None,
        description="Text of the top-k document chunks retrieved from ChromaDB.",
    )
    chunk_scores: Optional[list[float]] = Field(
        default=None,
        description="Cosine distance scores for each retrieved chunk (lower = more similar).",
    )
    chunk_metadata: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Metadata dicts for each retrieved chunk.",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "sql_query": (
                        "SELECT fy_yr, fq_lbl, ebitda_adj_pct "
                        "FROM erp_fin_qtr_export "
                        "WHERE dept_id_ref = 'D_402' "
                        "ORDER BY fy_yr, fq_lbl"
                    ),
                    "sql_results": [
                        {"fy_yr": 2024, "fq_lbl": "Q3", "ebitda_adj_pct": 0.229},
                        {"fy_yr": 2025, "fq_lbl": "Q4", "ebitda_adj_pct": 0.285},
                    ],
                    "sql_row_count": 2,
                    "retrieved_chunks": None,
                    "chunk_scores": None,
                    "chunk_metadata": None,
                }
            ]
        }
    }


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class QueryResponse(BaseModel):
    """
    Full response returned by POST /api/query.

    The frontend uses:
      - `answer`        → rendered in the chat bubble
      - `pipeline`      → drives the colour-coded PipelineBadge component
      - `artifacts`     → rendered in the collapsible ArtifactsPanel component
      - `processing_time_ms` → optional display in the UI footer
    """

    answer: str = Field(
        ...,
        description="Natural language answer synthesised by the LLM.",
        examples=[
            "Department D_402's total revenue for fiscal year 2025 was $98.5M "
            "($47.3M in Q3 and $51.2M in Q4)."
        ],
    )
    pipeline: PipelineType = Field(
        ...,
        description="The pipeline that was used to generate this answer.",
        examples=[PipelineType.SQL],
    )
    artifacts: Artifacts = Field(
        default_factory=Artifacts,
        description=(
            "Intermediate pipeline artifacts (generated SQL, retrieved chunks, etc.) "
            "for transparency and debugging. Fields are None when not applicable "
            "to the pipeline used."
        ),
    )
    processing_time_ms: Optional[float] = Field(
        default=None,
        description="Total server-side processing time in milliseconds.",
        examples=[1243.7],
    )
    error: Optional[str] = Field(
        default=None,
        description=(
            "Error message if the pipeline encountered a recoverable error "
            "but still returned a partial answer. None on full success."
        ),
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "answer": (
                        "Department D_402's total revenue for fiscal year 2025 was $98.5M "
                        "($47.3M in Q3 and $51.2M in Q4)."
                    ),
                    "pipeline": "SQL",
                    "artifacts": {
                        "sql_query": (
                            "SELECT fq_lbl, rev_raw_m FROM erp_fin_qtr_export "
                            "WHERE dept_id_ref = 'D_402' AND fy_yr = 2025"
                        ),
                        "sql_results": [
                            {"fq_lbl": "Q3", "rev_raw_m": 47.3},
                            {"fq_lbl": "Q4", "rev_raw_m": 51.2},
                        ],
                        "sql_row_count": 2,
                        "retrieved_chunks": None,
                        "chunk_scores": None,
                        "chunk_metadata": None,
                    },
                    "processing_time_ms": 1243.7,
                    "error": None,
                }
            ]
        }
    }


class HealthResponse(BaseModel):
    """
    Response returned by GET /api/health.

    Provides a top-level status and per-component readiness flags so that
    infrastructure monitoring tools can distinguish between a fully healthy
    service and one that is partially degraded.
    """

    status: str = Field(
        ...,
        description="Overall service status. 'ok' when all components are healthy.",
        examples=["ok", "degraded"],
    )
    components: dict[str, str] = Field(
        ...,
        description=(
            "Per-component status map. Keys are component names; "
            "values are 'ok', 'degraded', or 'unavailable'."
        ),
        examples=[
            {
                "sqlite": "ok",
                "chromadb": "ok",
                "openai": "ok",
            }
        ],
    )
    version: str = Field(
        default="1.0.0",
        description="API version string.",
        examples=["1.0.0"],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "status": "ok",
                    "components": {
                        "sqlite": "ok",
                        "chromadb": "ok",
                        "openai": "ok",
                    },
                    "version": "1.0.0",
                }
            ]
        }
    }
